name: Push Image

on:
  push:
    branches:
      - master
  pull_request:

  schedule:
    - cron: '0 15 * * *'

env:
  IMAGE_REPO: jeeaaasustest
  IMAGE_NAME: youtube-dl

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: $IMAGE_REPO
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $IMAGE_REPO/$IMAGE_NAME:beta
