name: Push New Release Version Image

on:
  workflow_dispatch:
  push:
    branches: 
      - 'master'
    paths:
      - 'release-versions/latest.txt'

env:
  IMAGE_REPO: jeeaaasustest
  IMAGE_NAME: youtube-dl

jobs:
  Push-New-Release-Version-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set tag
        run: |
          IMAGE_TAG=$(cat release-versions/latest.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set version
        run: |
          RELEASE_VERSION=$(cat release-versions/latest.txt)
          sed -i -E 's!(python.*install.*)(youtube_dl)!\1\2=='"$RELEASE_VERSION"'!i' Dockerfile

      - name: Remove updater
        run: rm --verbose -r root/etc/services.d/updater/

      - name: Print image tag
        run: |
          echo "Branch: $CI_ACTION_REF_NAME"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_TAG }}
