name: Push New Static Version Image

on:
  push:
    paths:
      - 'release-versions/latest.txt'

env:
  IMAGE_REPO: jeeaaasustest
  IMAGE_NAME: youtube-dl

jobs:
  Push-New-Static-Version-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure version
        run: |
          VERSION_TAG=$(cat ./release-versions/latest.txt)
          echo "Version: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          sed -i -E 's!(python.*install.*)(youtube_dl)!\1\2=='"$VERSION_TAG"'!i' ./Dockerfile

      - name: Remove updater
        run: rm --verbose -r ./root/etc/services.d/updater/

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:v${{ env.VERSION_TAG }}
