#!/usr/bin/with-contenv sh

#PUID=${PUID:-911}
#PGID=${PGID:-911}

#groupmod -o -g "$PGID" abc
#usermod -o -u "$PUID" abc

#chown abc:abc /config
#chown abc:abc /config.default
#chown abc:abc /downloads

addgroup \
  --force \
  --gid "$PGID" \
  abc
adduser \
  --gecos "" \
  --disabled-password \
  --no-create-home \
  --uid "$PUID" \
  --ingroup abc \
  --shell abc \
  abc 
