#!/usr/bin/with-contenv sh

addgroup \
  --force \
  --gid "$PGID" \
  abc
adduser \
  --gecos "" \
  --disabled-password \
  --no-create-home \
  --uid "$PUID" \
  --ingroup abc \
  --shell abc \
  abc 
