#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" users
usermod -o -u "$PUID" nobody

echo "
GID/UID
-------------------------------------
User uid:  $(id -u abc)
User gid:  $(id -g abc)
-------------------------------------
"
chown nobody:users /config
chown nobody:users /config.default
chown nobody:users /downloads
