#!/usr/bin/with-contenv sh

if [ $(getent group | grep abc) ]
  then
    echo "group abc already exists"
  else
    addgroup \
      --gid "$PGID" \
      abc
fi

adduser \
  --gecos "" \
  --disabled-password \
  --no-create-home \
  --uid "$PUID" \
  --ingroup abc \
  --shell abc \
  abc 
