#!/usr/bin/with-contenv bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown -R abc:abc /app/youtube-dl
chown -R abc:abc /config
chown -R abc:abc /downloads

chmod +x /app/youtube-dl/updater.sh
chmod +x /app/youtube-dl/youtube-dl.sh
