#!/usr/bin/with-contenv sh

if $youtubedl_webui
then
  echo "[web-ui] webserver is enabled."
else
  echo "[web-ui] webserver is disabled."
  [ -f '/etc/services.d/webserver' ] && rm -r /etc/services.d/webserver
fi
