#!/usr/bin/with-contenv bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /downloads
chown -R abc:abc /var/run/s6/services
chown -R abc:abc /root

chmod +x /app/youtube-dl/updater.sh
chmod +x /app/youtube-dl/youtube-dl.sh
