#!/bin/bash

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

mkdir -p /var/log/youtube-dl/
mkdir -p /var/log/youtube-dl-webui/

chown -R abc:abc /home/abc
chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /downloads
chown -R abc:abc /var/log
